### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Softsapiens** [jhabdas/material-ui-example#2]
Hello,
I try to build the project in an OSX environment with npm 3.3.9 and node 5.0.0 and get some problems:

- npm install returns these warnings:
npm WARN deprecated react-tools@0.12.2: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global react-tools@0.12.2 should be installed with -g

- gulp execution's log:
[15:45:19] Using gulpfile ~/Code/js/material-ui-example/gulpfile.js
[15:45:19] Starting 'setWatch'...
[15:45:19] Finished 'setWatch' after 77 μs
[15:45:19] Starting 'browserify'...
[15:45:19] Bundling app.js...
[15:45:19] Starting 'markup'...
[15:45:19] Starting 'less'...
[15:45:19] Starting 'fonts'...
[15:45:19] Starting 'muiFonts'...
[15:45:19] Finished 'fonts' after 27 ms
[15:45:19] Finished 'muiFonts' after 25 ms
[15:45:20] gulp-notify: [Compile Error] 'node_modules/material-ui/src/less/components.less' wasn't found. Tried - /Users/dani/Code/js/material-ui-example/src/less/node_modules/material-ui/src/less/components.less,node_modules/material-ui/src/less/components.less in file /Users/dani/Code/js/material-ui-example/src/less/main.less line no. 7
[15:45:20] Finished 'less' after 126 ms
[15:45:20] Finished 'markup' after 156 ms
[15:45:25] Bundled app.js in 5.21 s
[15:45:25] Finished 'browserify' after 5.24 s
[15:45:25] Starting 'build'...
[15:45:25] Finished 'build' after 6.15 μs
[15:45:25] Starting 'browserSync'...
[15:45:25] Finished 'browserSync' after 155 ms
[15:45:25] Starting 'watch'...
[15:45:25] Finished 'watch' after 14 ms
[15:45:25] Starting 'default'...
[15:45:25] Finished 'default' after 6.21 μs
[BS] Local URL: http://localhost:3000
[BS] External URL: http://192.168.1.104:3000
[BS] Serving files from: ./build
[BS] Serving files from: ./src
[BS] Watching files...

- browser console log (chrome) says:

Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1385 Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.warning @ app.js:1385
app.js:1385 Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.warning @ app.js:1385
app.js:1385 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `exports`.warning @ app.js:1385
app.js:944 Uncaught Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `exports`.
http://localhost:3000/main.css Failed to load resource: the server responded with a status of 404 (Not Found)

Thanks in advance, I'm looking forward to get the example run.
Dani

PD: the complete tree of installed packages:

material-ui-example@0.0.1 /Users/dani/Code/js/material-ui-example
├─┬ browser-sync@1.9.2
│ ├── browser-sync-client@1.0.2
│ ├─┬ commander@2.9.0
│ │ └── graceful-readlink@1.0.1
│ ├─┬ connect@3.4.0
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├─┬ finalhandler@0.4.0
│ │ │ ├─┬ on-finished@2.3.0
│ │ │ │ └── ee-first@1.1.1
│ │ │ └── unpipe@1.0.0
│ │ ├── parseurl@1.3.0
│ │ └── utils-merge@1.0.0
│ ├─┬ dev-ip@0.1.7
│ │ └── lodash@2.2.1
│ ├── easy-extender@2.3.1
│ ├─┬ eazy-logger@2.1.2
│ │ └── lodash@3.10.1
│ ├── emitter-steward@0.0.1
│ ├─┬ foxy@7.1.0
│ │ ├── cookie@0.1.5
│ │ ├── dev-ip@1.0.1
│ │ ├─┬ http-proxy@1.12.0
│ │ │ ├── eventemitter3@1.1.1
│ │ │ └── requires-port@0.0.1
│ │ ├── immutable@3.7.5
│ │ └─┬ meow@2.1.0
│ │   ├─┬ camelcase-keys@1.0.0
│ │   │ └── map-obj@1.0.1
│ │   └─┬ indent-string@1.2.2
│ │     └─┬ repeating@1.1.3
│ │       └─┬ is-finite@1.0.1
│ │         └── number-is-nan@1.0.0
│ ├─┬ glob-watcher@0.0.7
│ │ └─┬ gaze@0.5.2
│ │   └─┬ globule@0.1.0
│ │     ├─┬ glob@3.1.21
│ │     │ ├── graceful-fs@1.2.3
│ │     │ ├── inherits@1.0.2
│ │     │ └── minimatch@0.2.14
│ │     ├── lodash@1.0.2
│ │     └── minimatch@0.2.14
│ ├─┬ localtunnel@1.8.0
│ │ ├── openurl@1.1.0
│ │ ├─┬ request@2.65.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── bl@1.0.0
│ │ │ ├── caseless@0.11.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.0
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@1.0.0-rc3
│ │ │ │ └── async@1.5.0
│ │ │ ├─┬ har-validator@2.0.2
│ │ │ │ ├─┬ chalk@1.1.1
│ │ │ │ │ ├── ansi-styles@2.1.0
│ │ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ │ ├── strip-ansi@3.0.0
│ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ ├─┬ is-my-json-valid@2.12.3
│ │ │ │ │ ├── generate-function@2.0.0
│ │ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ │ └── is-property@1.0.2
│ │ │ │ │ └── jsonpointer@2.0.0
│ │ │ │ └─┬ pinkie-promise@1.0.0
│ │ │ │   └── pinkie@1.0.0
│ │ │ ├─┬ hawk@3.1.1
│ │ │ │ ├── boom@2.10.1
│ │ │ │ ├── cryptiles@2.0.5
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └── sntp@1.0.9
│ │ │ ├─┬ http-signature@0.11.0
│ │ │ │ ├── asn1@0.1.11
│ │ │ │ ├── assert-plus@0.1.5
│ │ │ │ └── ctype@0.5.3
│ │ │ ├── isstream@0.1.2
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├── node-uuid@1.4.3
│ │ │ ├── oauth-sign@0.8.0
│ │ │ ├── qs@5.2.0
│ │ │ ├── stringstream@0.0.5
│ │ │ ├── tough-cookie@2.2.0
│ │ │ └── tunnel-agent@0.4.1
│ │ └─┬ yargs@3.29.0
│ │   ├── camelcase@1.2.1
│ │   ├─┬ cliui@3.0.3
│ │   │ ├─┬ string-width@1.0.1
│ │   │ │ ├── code-point-at@1.0.0
│ │   │ │ ├── is-fullwidth-code-point@1.0.0
│ │   │ │ └─┬ strip-ansi@3.0.0
│ │   │ │   └── ansi-regex@2.0.0
│ │   │ ├─┬ strip-ansi@3.0.0
│ │   │ │ └── ansi-regex@2.0.0
│ │   │ └── wrap-ansi@1.0.0
│ │   ├── decamelize@1.1.1
│ │   ├─┬ os-locale@1.4.0
│ │   │ └─┬ lcid@1.0.0
│ │   │   └── invert-kv@1.0.0
│ │   ├── window-size@0.1.2
│ │   └── y18n@3.2.0
│ ├── lodash@2.4.2
│ ├── minimist@1.2.0
│ ├── object-path@0.8.1
│ ├── opn@1.0.2
│ ├── opt-merger@1.1.0
│ ├─┬ portscanner-plus@0.2.1
│ │ ├─┬ portscanner@1.0.0
│ │ │ └── async@0.1.15
│ │ └── q@1.4.1
│ ├─┬ resp-modifier@1.0.2
│ │ └─┬ minimatch@2.0.10
│ │   └─┬ brace-expansion@1.1.1
│ │     ├── balanced-match@0.2.1
│ │     └── concat-map@0.0.1
│ ├─┬ serve-index@1.7.2
│ │ ├─┬ accepts@1.2.13
│ │ │ └── negotiator@0.5.3
│ │ ├── batch@0.5.2
│ │ ├── escape-html@1.0.2
│ │ ├─┬ http-errors@1.3.1
│ │ │ ├── inherits@2.0.1
│ │ │ └── statuses@1.2.1
│ │ └─┬ mime-types@2.1.7
│ │   └── mime-db@1.19.0
│ ├─┬ serve-static@1.10.0
│ │ └─┬ send@0.13.0
│ │   ├── depd@1.0.1
│ │   ├── destroy@1.0.3
│ │   ├── etag@1.7.0
│ │   ├── fresh@0.3.0
│ │   └── range-parser@1.0.3
│ ├─┬ socket.io@1.3.7
│ │ ├─┬ debug@2.1.0
│ │ │ └── ms@0.6.2
│ │ ├─┬ engine.io@1.5.4
│ │ │ ├── base64id@0.1.0
│ │ │ ├─┬ debug@1.0.3
│ │ │ │ └── ms@0.6.2
│ │ │ ├─┬ engine.io-parser@1.2.2
│ │ │ │ ├── after@0.8.1
│ │ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ │ ├── blob@0.0.4
│ │ │ │ └── utf8@2.1.0
│ │ │ └─┬ ws@0.8.0
│ │ │   ├─┬ bufferutil@1.2.1
│ │ │   │ └── bindings@1.2.1
│ │ │   ├── options@0.0.6
│ │ │   ├── ultron@1.0.2
│ │ │   └── utf-8-validate@1.2.1
│ │ ├── has-binary-data@0.1.3
│ │ ├─┬ socket.io-adapter@0.3.1
│ │ │ ├─┬ debug@1.0.2
│ │ │ │ └── ms@0.6.2
│ │ │ ├── object-keys@1.0.1
│ │ │ └─┬ socket.io-parser@2.2.2
│ │ │   └── debug@0.7.4
│ │ ├─┬ socket.io-client@1.3.7
│ │ │ ├── backo2@1.0.2
│ │ │ ├── component-bind@1.0.0
│ │ │ ├── component-emitter@1.1.2
│ │ │ ├── debug@0.7.4
│ │ │ ├─┬ engine.io-client@1.5.4
│ │ │ │ ├── component-inherit@0.0.3
│ │ │ │ ├─┬ debug@1.0.4
│ │ │ │ │ └── ms@0.6.2
│ │ │ │ ├─┬ has-cors@1.0.3
│ │ │ │ │ └── global@2.0.1
│ │ │ │ ├── parsejson@0.0.1
│ │ │ │ ├── parseqs@0.0.2
│ │ │ │ ├── parseuri@0.0.4
│ │ │ │ └── xmlhttprequest@1.5.0
│ │ │ ├── has-binary@0.1.6
│ │ │ ├── object-component@0.0.3
│ │ │ ├─┬ parseuri@0.0.2
│ │ │ │ └── better-assert@1.0.2
│ │ │ └── to-array@0.1.3
│ │ └─┬ socket.io-parser@2.2.4
│ │   ├── benchmark@1.0.0
│ │   ├── debug@0.7.4
│ │   └── json3@3.2.6
│ ├─┬ tfunk@3.0.1
│ │ ├─┬ chalk@0.5.1
│ │ │ ├── ansi-styles@1.1.0
│ │ │ ├─┬ has-ansi@0.1.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ ├── strip-ansi@0.3.0
│ │ │ └── supports-color@0.2.0
│ │ └── object-path@0.9.2
│ └── ua-parser-js@0.7.9
├─┬ browserify@7.1.0
│ ├── assert@1.1.2
│ ├─┬ browser-pack@3.2.0
│ │ ├─┬ combine-source-map@0.3.0
│ │ │ ├── convert-source-map@0.3.5
│ │ │ └─┬ inline-source-map@0.3.1
│ │ │   └── source-map@0.3.0
│ │ └─┬ through2@0.5.1
│ │   ├─┬ readable-stream@1.0.33
│ │   │ └── inherits@2.0.1
│ │   └── xtend@3.0.0
│ ├─┬ browser-resolve@1.10.1
│ │ └── resolve@1.1.6
│ ├─┬ browserify-zlib@0.1.4
│ │ └── pako@0.2.8
│ ├─┬ buffer@3.5.1
│ │ ├── base64-js@0.0.8
│ │ ├── ieee754@1.1.6
│ │ └── is-array@1.0.1
│ ├── builtins@0.0.7
│ ├── commondir@0.0.1
│ ├─┬ concat-stream@1.4.10
│ │ ├── inherits@2.0.1
│ │ ├── readable-stream@1.1.13
│ │ └── typedarray@0.0.6
│ ├─┬ console-browserify@1.1.0
│ │ └── date-now@0.1.4
│ ├── constants-browserify@0.0.1
│ ├─┬ crypto-browserify@3.11.0
│ │ ├─┬ browserify-cipher@1.0.0
│ │ │ ├─┬ browserify-aes@1.0.5
│ │ │ │ ├── buffer-xor@1.0.3
│ │ │ │ └── inherits@2.0.1
│ │ │ ├─┬ browserify-des@1.0.0
│ │ │ │ ├─┬ des.js@1.0.0
│ │ │ │ │ ├── inherits@2.0.1
│ │ │ │ │ └── minimalistic-assert@1.0.0
│ │ │ │ └── inherits@2.0.1
│ │ │ └── evp_bytestokey@1.0.0
│ │ ├─┬ browserify-sign@4.0.0
│ │ │ ├── bn.js@4.1.1
│ │ │ ├── browserify-rsa@4.0.0
│ │ │ ├─┬ elliptic@6.0.2
│ │ │ │ ├── brorand@1.0.5
│ │ │ │ ├─┬ hash.js@1.0.3
│ │ │ │ │ └── inherits@2.0.1
│ │ │ │ └── inherits@2.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ parse-asn1@5.0.0
│ │ │   └─┬ asn1.js@4.0.0
│ │ │     └── inherits@2.0.1
│ │ ├── create-ecdh@4.0.0
│ │ ├─┬ create-hash@1.1.2
│ │ │ ├─┬ cipher-base@1.0.2
│ │ │ │ └── inherits@2.0.1
│ │ │ ├── inherits@2.0.1
│ │ │ └── ripemd160@1.0.1
│ │ ├─┬ create-hmac@1.1.4
│ │ │ └── inherits@2.0.1
│ │ ├─┬ diffie-hellman@5.0.0
│ │ │ └── miller-rabin@4.0.0
│ │ ├── inherits@2.0.1
│ │ ├── pbkdf2@3.0.4
│ │ ├── public-encrypt@4.0.0
│ │ └── randombytes@2.0.1
│ ├── deep-equal@0.2.2
│ ├── defined@0.0.0
│ ├─┬ deps-sort@1.3.9
│ │ └─┬ JSONStream@1.0.6
│ │   └── jsonparse@1.2.0
│ ├── domain-browser@1.1.4
│ ├─┬ duplexer2@0.0.2
│ │ └─┬ readable-stream@1.1.13
│ │   └── inherits@2.0.1
│ ├── events@1.0.2
│ ├─┬ glob@4.5.3
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ └── once@1.3.2
│ ├─┬ http-browserify@1.7.0
│ │ ├── Base64@0.2.1
│ │ └── inherits@2.0.1
│ ├── https-browserify@0.0.1
│ ├── inherits@2.0.1
│ ├─┬ insert-module-globals@6.6.3
│ │ ├─┬ combine-source-map@0.6.1
│ │ │ ├── convert-source-map@1.1.1
│ │ │ ├── inline-source-map@0.5.0
│ │ │ ├── lodash.memoize@3.0.4
│ │ │ └── source-map@0.4.4
│ │ ├── is-buffer@1.1.0
│ │ ├─┬ JSONStream@1.0.6
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ lexical-scope@1.2.0
│ │ │ └── astw@2.0.0
│ │ └── process@0.11.2
│ ├── isarray@0.0.1
│ ├─┬ JSONStream@0.8.4
│ │ └── jsonparse@0.0.5
│ ├─┬ labeled-stream-splicer@1.0.2
│ │ ├── inherits@2.0.1
│ │ └─┬ stream-splicer@1.3.2
│ │   ├── inherits@2.0.1
│ │   ├── readable-stream@1.1.13
│ │   └─┬ readable-wrap@1.0.0
│ │     └─┬ readable-stream@1.1.13
│ │       └── inherits@2.0.1
│ ├─┬ module-deps@3.9.1
│ │ ├── defined@1.0.0
│ │ ├─┬ detective@4.3.1
│ │ │ └── defined@1.0.0
│ │ ├── inherits@2.0.1
│ │ ├─┬ JSONStream@1.0.6
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ parents@1.0.1
│ │ │ └── path-platform@0.11.15
│ │ ├── readable-stream@1.1.13
│ │ ├── resolve@1.1.6
│ │ └─┬ stream-combiner2@1.0.2
│ │   └─┬ through2@0.5.1
│ │     ├─┬ readable-stream@1.0.33
│ │     │ └── inherits@2.0.1
│ │     └── xtend@3.0.0
│ ├── os-browserify@0.1.2
│ ├─┬ parents@0.0.3
│ │ └── path-platform@0.0.1
│ ├── path-browserify@0.0.0
│ ├── process@0.8.0
│ ├── punycode@1.2.4
│ ├── querystring-es3@0.2.1
│ ├─┬ readable-stream@1.1.13
│ │ └── core-util-is@1.0.1
│ ├── resolve@0.7.4
│ ├── shallow-copy@0.0.1
│ ├─┬ shasum@1.0.2
│ │ ├─┬ json-stable-stringify@0.0.1
│ │ │ └── jsonify@0.0.0
│ │ └─┬ sha.js@2.4.4
│ │   └── inherits@2.0.1
│ ├── shell-quote@0.0.1
│ ├─┬ stream-browserify@1.0.0
│ │ ├── inherits@2.0.1
│ │ └── readable-stream@1.1.13
│ ├── string_decoder@0.10.31
│ ├── subarg@1.0.0
│ ├─┬ syntax-error@1.1.4
│ │ └── acorn@1.2.2
│ ├─┬ through2@1.1.1
│ │ └─┬ readable-stream@1.1.13
│ │   └── inherits@2.0.1
│ ├─┬ timers-browserify@1.4.1
│ │ └── process@0.11.2
│ ├── tty-browserify@0.0.0
│ ├─┬ umd@2.1.0
│ │ ├─┬ rfile@1.0.0
│ │ │ ├── callsite@1.0.0
│ │ │ └── resolve@0.3.1
│ │ ├─┬ ruglify@1.0.0
│ │ │ └─┬ uglify-js@2.2.5
│ │ │   └─┬ optimist@0.3.7
│ │ │     └── wordwrap@0.0.3
│ │ └─┬ uglify-js@2.4.24
│ │   ├── async@0.2.10
│ │   ├── source-map@0.1.34
│ │   ├── uglify-to-browserify@1.0.2
│ │   └─┬ yargs@3.5.4
│ │     ├── window-size@0.1.0
│ │     └── wordwrap@0.0.2
│ ├─┬ url@0.10.3
│ │ ├── punycode@1.3.2
│ │ └── querystring@0.2.0
│ ├─┬ util@0.10.3
│ │ └── inherits@2.0.1
│ ├─┬ vm-browserify@0.0.4
│ │ └── indexof@0.0.1
│ └── xtend@3.0.0
├─┬ gulp@3.9.0
│ ├── archy@1.0.0
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├── escape-string-regexp@1.0.3
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.0
│ │ └── supports-color@2.0.0
│ ├── deprecated@0.0.1
│ ├── interpret@0.6.6
│ ├─┬ liftoff@2.2.0
│ │ ├── extend@2.0.1
│ │ ├─┬ findup-sync@0.3.0
│ │ │ └─┬ glob@5.0.15
│ │ │   ├── inherits@2.0.1
│ │ │   └── path-is-absolute@1.0.0
│ │ ├── flagged-respawn@0.3.1
│ │ ├─┬ rechoir@0.6.2
│ │ │ └── resolve@1.1.6
│ │ └── resolve@1.1.6
│ ├─┬ orchestrator@0.3.7
│ │ ├── end-of-stream@0.1.5
│ │ ├── sequencify@0.0.7
│ │ └── stream-consume@0.1.0
│ ├── pretty-hrtime@1.0.1
│ ├── semver@4.3.6
│ ├─┬ tildify@1.1.2
│ │ └── os-homedir@1.0.1
│ ├─┬ v8flags@2.0.10
│ │ └── user-home@1.1.1
│ └─┬ vinyl-fs@0.3.14
│   ├── defaults@1.0.3
│   ├─┬ glob-stream@3.1.18
│   │ ├─┬ glob@4.5.3
│   │ │ └── inherits@2.0.1
│   │ ├─┬ glob2base@0.0.12
│   │ │ └── find-index@0.1.1
│   │ ├── ordered-read-streams@0.1.0
│   │ ├─┬ through2@0.6.5
│   │ │ └── readable-stream@1.0.33
│   │ └── unique-stream@1.0.0
│   ├── glob-watcher@0.0.6
│   ├── graceful-fs@3.0.8
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├─┬ strip-bom@1.0.0
│   │ └── first-chunk-stream@1.0.0
│   ├─┬ through2@0.6.5
│   │ └─┬ readable-stream@1.0.33
│   │   └── inherits@2.0.1
│   └─┬ vinyl@0.4.6
│     └── clone@0.2.0
├─┬ gulp-autoprefixer@2.3.1
│ ├─┬ autoprefixer-core@5.2.1
│ │ ├── browserslist@0.4.0
│ │ ├── caniuse-db@1.0.30000359
│ │ └── num2fraction@1.2.2
│ ├── object-assign@2.1.1
│ ├─┬ postcss@4.1.16
│ │ ├── es6-promise@2.3.0
│ │ ├── js-base64@2.1.9
│ │ └─┬ source-map@0.4.4
│ │   └── amdefine@1.0.0
│ ├─┬ through2@0.6.5
│ │ └─┬ readable-stream@1.0.33
│ │   └── inherits@2.0.1
│ └─┬ vinyl-sourcemaps-apply@0.1.4
│   └── source-map@0.1.43
├─┬ gulp-less@3.0.3
│ ├─┬ accord@0.15.2
│ │ ├── convert-source-map@0.4.1
│ │ ├─┬ fobject@0.0.3
│ │ │ └── graceful-fs@3.0.8
│ │ ├─┬ glob@4.5.3
│ │ │ └── inherits@2.0.1
│ │ ├── indx@0.2.3
│ │ ├── lodash@3.10.1
│ │ ├── resolve@1.1.6
│ │ └── when@3.7.4
│ ├─┬ less@2.5.3
│ │ ├─┬ errno@0.1.4
│ │ │ └── prr@0.0.0
│ │ ├── graceful-fs@3.0.8
│ │ ├── image-size@0.3.5
│ │ ├── mime@1.3.4
│ │ ├─┬ promise@6.1.0
│ │ │ └── asap@1.0.0
│ │ └── source-map@0.4.4
│ └─┬ through2@0.6.5
│   └─┬ readable-stream@1.0.33
│     └── inherits@2.0.1
├─┬ gulp-notify@2.2.0
│ ├─┬ lodash.template@3.6.2
│ │ ├── lodash._basecopy@3.0.1
│ │ ├── lodash._basetostring@3.0.1
│ │ ├── lodash._basevalues@3.0.0
│ │ ├── lodash._isiterateecall@3.0.9
│ │ ├── lodash.escape@3.0.0
│ │ ├─┬ lodash.keys@3.1.2
│ │ │ ├── lodash._getnative@3.9.1
│ │ │ ├── lodash.isarguments@3.0.4
│ │ │ └── lodash.isarray@3.0.4
│ │ ├── lodash.restparam@3.6.1
│ │ └── lodash.templatesettings@3.1.0
│ ├─┬ node-notifier@4.3.1
│ │ ├─┬ cli-usage@0.1.2
│ │ │ ├── marked@0.3.5
│ │ │ ├─┬ marked-terminal@1.6.1
│ │ │ │ ├─┬ cardinal@0.5.0
│ │ │ │ │ ├── ansicolors@0.2.1
│ │ │ │ │ └─┬ redeyed@0.5.0
│ │ │ │ │   └── esprima-fb@12001.1.0-dev-harmony-fb
│ │ │ │ ├─┬ chalk@1.1.1
│ │ │ │ │ ├── ansi-styles@2.1.0
│ │ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ │ ├── strip-ansi@3.0.0
│ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ ├─┬ cli-table@0.3.1
│ │ │ │ │ └── colors@1.0.3
│ │ │ │ ├─┬ lodash.assign@3.2.0
│ │ │ │ │ └── lodash._createassigner@3.1.1
│ │ │ │ └── node-emoji@0.1.0
│ │ │ └── minimist@0.2.0
│ │ ├── growly@1.2.0
│ │ ├─┬ lodash.clonedeep@3.0.2
│ │ │ ├─┬ lodash._baseclone@3.3.0
│ │ │ │ ├── lodash._arraycopy@3.0.0
│ │ │ │ ├── lodash._arrayeach@3.0.0
│ │ │ │ ├── lodash._baseassign@3.2.0
│ │ │ │ └── lodash._basefor@3.0.2
│ │ │ └── lodash._bindcallback@3.0.1
│ │ ├── shellwords@0.1.0
│ │ └─┬ which@1.2.0
│ │   └─┬ is-absolute@0.1.7
│ │     └── is-relative@0.1.3
│ ├─┬ node.extend@1.1.5
│ │ └── is@3.1.0
│ └─┬ through2@0.6.5
│   └─┬ readable-stream@1.0.33
│     └── inherits@2.0.1
├─┬ gulp-sourcemaps@1.6.0
│ ├── convert-source-map@1.1.1
│ ├── graceful-fs@4.1.2
│ ├─┬ strip-bom@2.0.0
│ │ └── is-utf8@0.2.0
│ ├─┬ through2@2.0.0
│ │ └─┬ readable-stream@2.0.4
│ │   ├── inherits@2.0.1
│ │   ├── process-nextick-args@1.0.3
│ │   └── util-deprecate@1.0.2
│ └─┬ vinyl@1.1.0
│   ├── clone@1.0.2
│   └── clone-stats@0.0.1
├─┬ gulp-util@3.0.7
│ ├── array-differ@1.0.0
│ ├── array-uniq@1.0.2
│ ├── beeper@1.1.0
│ ├─┬ chalk@1.1.1
│ │ ├── ansi-styles@2.1.0
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.0.0
│ │ ├── strip-ansi@3.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ dateformat@1.0.11
│ │ └── get-stdin@4.0.1
│ ├─┬ fancy-log@1.1.0
│ │ └─┬ chalk@1.1.1
│ │   ├── ansi-styles@2.1.0
│ │   ├─┬ has-ansi@2.0.0
│ │   │ └── ansi-regex@2.0.0
│ │   ├── strip-ansi@3.0.0
│ │   └── supports-color@2.0.0
│ ├─┬ gulplog@1.0.0
│ │ └── glogg@1.0.0
│ ├─┬ has-gulplog@0.1.0
│ │ └── sparkles@1.0.0
│ ├── lodash._reescape@3.0.0
│ ├── lodash._reevaluate@3.0.0
│ ├── lodash._reinterpolate@3.0.0
│ ├── multipipe@0.1.2
│ ├── object-assign@3.0.0
│ ├── replace-ext@0.0.1
│ ├── through2@2.0.0
│ └── vinyl@0.5.3
├── material-ui@0.13.1
├── pretty-hrtime@0.2.2
├─┬ react@0.14.2
│ ├─┬ envify@3.4.0
│ │ └─┬ jstransform@10.1.0
│ │   └── esprima-fb@13001.1001.0-dev-harmony-fb
│ └─┬ fbjs@0.3.2
│   ├── core-js@1.2.6
│   ├─┬ loose-envify@1.1.0
│   │ └── js-tokens@1.0.2
│   ├─┬ promise@7.0.4
│   │ └── asap@2.0.3
│   └── whatwg-fetch@0.9.0
├── react-addons-create-fragment@0.14.2
├── react-addons-pure-render-mixin@0.14.2
├── react-addons-transition-group@0.14.2
├── react-addons-update@0.14.2
├── react-dom@0.14.2
├─┬ react-router@0.13.5
│ ├── can-use-dom@0.1.0
│ ├── invariant@2.1.2
│ └── qs@2.4.1
├─┬ react-tap-event-plugin@0.2.1
│ └── fbjs@0.2.1
├─┬ reactify@0.17.1
│ ├─┬ jstransform@8.2.0
│ │ ├── base62@0.1.1
│ │ ├── esprima-fb@8001.1001.0-dev-harmony-fb
│ │ └── source-map@0.1.31
│ ├─┬ react-tools@0.12.2
│ │ ├─┬ commoner@0.10.4
│ │ │ ├─┬ glob@5.0.15
│ │ │ │ └── inherits@2.0.1
│ │ │ ├── graceful-fs@4.1.2
│ │ │ ├── iconv-lite@0.4.13
│ │ │ ├── private@0.1.6
│ │ │ └─┬ recast@0.10.37
│ │ │   ├── ast-types@0.8.12
│ │ │   ├── esprima-fb@15001.1001.0-dev-harmony-fb
│ │ │   └── source-map@0.5.3
│ │ └─┬ jstransform@8.2.0
│ │   └── esprima-fb@8001.1001.0-dev-harmony-fb
│ └── through@2.3.8
├── require-dir@0.1.0
├── underscore@1.8.3
├─┬ vinyl-source-stream@1.1.0
│ ├─┬ through2@0.6.5
│ │ └─┬ readable-stream@1.0.33
│ │   └── inherits@2.0.1
│ └─┬ vinyl@0.4.6
│   └── clone@0.2.0
└─┬ watchify@2.6.2
  ├─┬ browserify@9.0.8
  │ ├── assert@1.3.0
  │ ├─┬ browser-pack@4.0.4
  │ │ ├── defined@1.0.0
  │ │ ├─┬ JSONStream@1.0.6
  │ │ │ └── jsonparse@1.2.0
  │ │ └── umd@3.0.1
  │ ├── deep-equal@1.0.1
  │ ├── glob@4.5.3
  │ ├─┬ has@1.0.1
  │ │ └── function-bind@1.0.2
  │ ├── inherits@2.0.1
  │ ├─┬ JSONStream@0.10.0
  │ │ └── jsonparse@0.0.5
  │ ├── parents@1.0.1
  │ ├── process@0.10.1
  │ ├─┬ read-only-stream@1.1.1
  │ │ └─┬ readable-stream@1.1.13
  │ │   └── inherits@2.0.1
  │ ├── readable-stream@1.1.13
  │ ├── resolve@1.1.6
  │ ├─┬ through2@1.1.1
  │ │ └── xtend@4.0.1
  │ └── xtend@3.0.0
  ├─┬ chokidar@0.12.6
  │ ├── async-each@0.1.6
  │ ├─┬ fsevents@0.3.8
  │ │ └── nan@2.1.0
  │ └─┬ readdirp@1.3.0
  │   ├── graceful-fs@2.0.3
  │   ├─┬ minimatch@0.2.14
  │   │ ├── lru-cache@2.7.0
  │   │ └── sigmund@1.0.1
  │   └─┬ readable-stream@1.0.33
  │     └── inherits@2.0.1
  ├─┬ through2@0.5.1
  │ ├── readable-stream@1.0.33
  │ └── xtend@3.0.0
  └── xtend@4.0.1

**Comment by jhabdas** [comment]
Thanks for the report. I spiked this repo about a year ago under an older
version of React and it needs to be upgraded to 0.14 now to quell the
warnings. More info in #1 (plus related details on the issue you're
experiencing). At this moment I don't have any intention of upgrading given
the nature of this repo. But if you check out the other issue mentioned I
left a path to help lead forward. Hope that helps!

**Comment by Softsapiens** [comment]
Ok, thanks
